#!/usr/bin/env bash
#  Configure Nginx so that its HTTP response contains
# a custom header

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

printf %s "server {
    listen 80;
    listen [::]:80;
    
    root   /var/www/html;
    index  index.html index.htm;
    location / {
        add_header X-Served-By $HOSTNAME;
    }
}" > /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx restart
