#!/usr/bin/env bash
# Bash script that configures a server to run Nginx listening on port 80

#  List all processes listening on port 80
sudo lsof -i tcp:80

# Kill all processes listening on port 80
sudo kill $(lsof -t -i:80)

# restart nginx
sudo service nginx restart
