#!/usr/bin/env bash
# 

#  List all processes listening on port 80
sudo lsof -i tcp:80

# Kill all processes listening on port 80
sudo kill $(lsof -t -i:80)

# restart nginx
sudo service nginx restart









# # Stop Apache processes
# pkill apache2

# # If port 80 for IPv4 is being listened to, it is changed to port 8080
# if grep -q "listen 80" /etc/nginx/sites-available/default ; then
#     sed -i "s/listen 80/listen 8080/" /etc/nginx/sites-available/default
# fi

# # If port 80 for IPv6 is being listened to, it is changed to port 8080
# if grep -q "listen \[::\]:80" /etc/nginx/sites-available/default ; then
#     sed -i "s/listen \[::\]:80/listen \[::\]:8080/" /etc/nginx/sites-available/default
# fi

# # Update Nginx settings file owner and group
# chown nginx:nginx /etc/nginx/nginx.conf

# # Update Nginx settings file permissions
# chmod 0644 /etc/nginx/nginx.conf

# # Start the nginx service as the nginx user
# su nginx -c "service nginx start"