#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes:
#+ display hours from 0 to 12 and display minutes from 1 to 59

HOUR=0

while [ "$HOUR" -le 12 ]
do
    echo "Hour: $HOUR"
    minute=1
    while [ $minute -le 59 ]
    do
        echo "$minute"
        (( minute++ ))
    done
    (( HOUR++ ))
done
